/// The formulas Quick AL ships with, and the ones a workshop has changed.
library;

import '../model/formula_slot.dart';
import '../model/formula_window_key.dart';

/// One profile and every piece cut from it for a given window.
class SectionFormulas {
  const SectionFormulas(this.section, this.pieces);

  /// The profile -- "DC30C", "M24".
  final String section;

  /// In the order the engine cuts them. Two pieces can share a label -- a
  /// sliding window takes two M23 uprights -- so position, not name, is what
  /// identifies a piece.
  final List<FormulaSlot> pieces;
}

/// Every formula the app was built with.
///
/// Generated by tool/build_formula_catalogue.dart from the engine's own
/// output, and checked against it at 211,108 sample points before shipping.
/// Nothing in here is written by hand, and nothing in the app writes to it --
/// a workshop's own changes are kept separately, so "reset" always has
/// something true to go back to.
class FormulaCatalogue {
  FormulaCatalogue._(this._formulas, this._windows);

  /// Every distinct formula, once. The whole engine is 134 of them.
  final List<String> _formulas;

  /// windowKey -> configKey -> section -> [[label, formulaIndex], ...]
  final Map<String, Map<String, Map<String, List<dynamic>>>> _windows;

  /// Reads a catalogue from its JSON.
  ///
  /// Where that JSON comes from is somebody else's business -- the app reads
  /// it from its assets, the parity harness from a file on disk, a test from a
  /// map it wrote itself. Keeping the loading out of here is what lets the
  /// harness run the app's own cutting code outside a Flutter app at all.
  static FormulaCatalogue fromJson(Map<String, dynamic> json) {
    final List<String> formulas = (json['formulas'] as List<dynamic>).cast<String>();
    final Map<String, Map<String, Map<String, List<dynamic>>>> windows =
        <String, Map<String, Map<String, List<dynamic>>>>{};
    (json['windows'] as Map<String, dynamic>).forEach((String windowKey, dynamic value) {
      final Map<String, dynamic> configs =
          (value as Map<String, dynamic>)['configs'] as Map<String, dynamic>;
      windows[windowKey] = configs.map((String configKey, dynamic sections) {
        return MapEntry<String, Map<String, List<dynamic>>>(
          configKey,
          (sections as Map<String, dynamic>).map(
            (String section, dynamic pieces) =>
                MapEntry<String, List<dynamic>>(section, pieces as List<dynamic>),
          ),
        );
      });
    });
    return FormulaCatalogue._(formulas, windows);
  }

  /// What a window's configuration is made of -- collarType, lockType and the
  /// rest.
  ///
  /// Taken from the catalogue rather than written down anywhere else, so the
  /// key the app builds is always the shape the catalogue was written in.
  /// Every configuration of a window has the same dimensions, so the first one
  /// answers for all.
  Set<String> dimensionsFor(String windowKey) {
    final Map<String, Map<String, List<dynamic>>>? configs = _windows[windowKey];
    if (configs == null || configs.isEmpty) return const <String>{};
    final String first = configs.keys.first;
    if (first.isEmpty) return const <String>{};
    return first
        .split('|')
        .map((String part) => part.split('=').first)
        .toSet();
  }

  /// Whether this window is one the catalogue describes at all.
  bool knows(String windowKey) => _windows.containsKey(windowKey);

  /// The formulas Quick AL ships for this exact window, before any of the
  /// workshop's own changes.
  ///
  /// Null when the catalogue has nothing for it -- a configuration the engine
  /// refuses, such as a collar type this window does not offer.
  List<SectionFormulas>? shippedFor(FormulaWindowKey key) {
    final Map<String, List<dynamic>>? sections = _windows[key.windowKey]?[key.configKey];
    if (sections == null) return null;

    final bool isFabrication = key.context == 'fabrication';
    final List<SectionFormulas> out = <SectionFormulas>[];

    // Sorted, so the screen lists profiles in the same order every time; the
    // pieces inside a section keep the engine's order, which is the order they
    // are cut in.
    final List<String> names = sections.keys.toList()..sort();
    for (final String section in names) {
      final List<dynamic> pieces = sections[section]!;
      out.add(SectionFormulas(
        section,
        <FormulaSlot>[
          for (final dynamic piece in pieces)
            FormulaSlot(
              section: section,
              label: (piece as List<dynamic>)[0] as String,
              stored: _formulas[piece[1] as int],
              isFabrication: isFabrication,
            ),
        ],
      ));
    }
    return out;
  }

  /// The shipped formula for one piece, or null if there is no such piece.
  String? shippedFormulaAt(String windowKey, String configKey, String section, int index) {
    final List<dynamic>? pieces = _windows[windowKey]?[configKey]?[section];
    if (pieces == null || index < 0 || index >= pieces.length) return null;
    return _formulas[(pieces[index] as List<dynamic>)[1] as int];
  }

  /// Everywhere else this same piece is cut by this same sum.
  ///
  /// A workshop that shortens the sliding window's left upright usually means
  /// it for every collar type, not only the one they happened to have open --
  /// but not always, so this only says where the change *could* go, and the
  /// workshop is asked before it goes there. Matching is by profile, label,
  /// position and the formula they start from: a configuration that already
  /// cuts this piece differently is left alone, because whatever made it
  /// different is not something to quietly overwrite.
  List<String> configsSharing({
    required String windowKey,
    required String section,
    required int index,
    required String label,
    required String formula,
  }) {
    final Map<String, Map<String, List<dynamic>>>? configs = _windows[windowKey];
    if (configs == null) return const <String>[];

    final List<String> found = <String>[];
    configs.forEach((String configKey, Map<String, List<dynamic>> sections) {
      final List<dynamic>? pieces = sections[section];
      if (pieces == null || index >= pieces.length) return;
      final List<dynamic> piece = pieces[index] as List<dynamic>;
      if (piece[0] != label) return;
      if (_formulas[piece[1] as int] != formula) return;
      found.add(configKey);
    });
    return found;
  }

  /// How many pieces this window is cut into, across every profile.
  int pieceCountFor(FormulaWindowKey key) {
    final Map<String, List<dynamic>>? sections = _windows[key.windowKey]?[key.configKey];
    if (sections == null) return 0;
    return sections.values.fold(0, (int sum, List<dynamic> pieces) => sum + pieces.length);
  }
}
