/// The formulas Quick AL ships with, and the ones a workshop has changed.
library;

import '../model/formula_slot.dart';
import '../model/formula_window_key.dart';

/// One profile and every piece cut from it for a given window.
class SectionFormulas {
  const SectionFormulas(this.section, this.pieces, {String? displayName})
      : _displayName = displayName;

  /// The profile -- "DC30C", "M24" -- or, for glass, a steady name like
  /// "glass1" that a workshop's saved formulas hang off.
  final String section;

  final String? _displayName;

  /// What a fabricator sees at the head of this group.
  ///
  /// Separate from [section] because glass panes are shown as "Glass 2 · Fix"
  /// and that wording could change; what a workshop has saved must not move
  /// when it does.
  String get displayName => _displayName ?? section;

  /// True for the panes of glass rather than the lengths of aluminium.
  ///
  /// They are formulas either way and a workshop edits them the same way, but
  /// only one of them is cut from a bar: glass sent to the length optimizer
  /// would come back arranged into stock lengths nobody can cut it from.
  bool get isGlass => section.startsWith('glass');

  /// In the order the engine cuts them. Two pieces can share a label -- a
  /// sliding window takes two M23 uprights -- so position, not name, is what
  /// identifies a piece.
  final List<FormulaSlot> pieces;
}

/// Every formula the app was built with.
///
/// Generated by tool/build_formula_catalogue.dart from the engine's own
/// output, and checked against it at 211,108 sample points before shipping.
/// Nothing in here is written by hand, and nothing in the app writes to it --
/// a workshop's own changes are kept separately, so "reset" always has
/// something true to go back to.
class FormulaCatalogue {
  FormulaCatalogue._(this._formulas, this._windows, this._glass);

  /// Every distinct formula, once.
  final List<String> _formulas;

  /// windowKey -> configKey -> section -> [[label, formulaIndex], ...]
  final Map<String, Map<String, Map<String, List<dynamic>>>> _windows;

  /// windowKey -> configKey -> the panes of glass, in cutting order.
  ///
  /// Kept apart from the aluminium because only one of the two is cut from a
  /// bar. Each pane carries a height and a width formula, and on the panel
  /// windows the job the panel does -- Slide or Fix -- which the engine's own
  /// rail labels name.
  final Map<String, Map<String, List<dynamic>>> _glass;

  /// Reads a catalogue from its JSON.
  ///
  /// Where that JSON comes from is somebody else's business -- the app reads
  /// it from its assets, the parity harness from a file on disk, a test from a
  /// map it wrote itself. Keeping the loading out of here is what lets the
  /// harness run the app's own cutting code outside a Flutter app at all.
  static FormulaCatalogue fromJson(Map<String, dynamic> json) {
    final List<String> formulas = (json['formulas'] as List<dynamic>).cast<String>();
    final Map<String, Map<String, Map<String, List<dynamic>>>> windows =
        <String, Map<String, Map<String, List<dynamic>>>>{};
    final Map<String, Map<String, List<dynamic>>> glass =
        <String, Map<String, List<dynamic>>>{};

    (json['windows'] as Map<String, dynamic>).forEach((String windowKey, dynamic value) {
      final Map<String, dynamic> window = value as Map<String, dynamic>;
      final Map<String, dynamic> configs = window['configs'] as Map<String, dynamic>;
      windows[windowKey] = configs.map((String configKey, dynamic sections) {
        return MapEntry<String, Map<String, List<dynamic>>>(
          configKey,
          (sections as Map<String, dynamic>).map(
            (String section, dynamic pieces) =>
                MapEntry<String, List<dynamic>>(section, pieces as List<dynamic>),
          ),
        );
      });

      final Object? panes = window['glass'];
      if (panes is Map<String, dynamic>) {
        glass[windowKey] = panes.map(
          (String configKey, dynamic list) =>
              MapEntry<String, List<dynamic>>(configKey, list as List<dynamic>),
        );
      }
    });

    return FormulaCatalogue._(formulas, windows, glass);
  }

  /// What a window's configuration is made of -- collarType, lockType and the
  /// rest.
  ///
  /// Taken from the catalogue rather than written down anywhere else, so the
  /// key the app builds is always the shape the catalogue was written in.
  /// Every configuration of a window has the same dimensions, so the first one
  /// answers for all.
  Set<String> dimensionsFor(String windowKey) {
    final Map<String, Map<String, List<dynamic>>>? configs = _windows[windowKey];
    if (configs == null || configs.isEmpty) return const <String>{};
    final String first = configs.keys.first;
    if (first.isEmpty) return const <String>{};
    return first
        .split('|')
        .map((String part) => part.split('=').first)
        .toSet();
  }

  /// Whether this window is one the catalogue describes at all.
  bool knows(String windowKey) => _windows.containsKey(windowKey);

  /// The formulas Quick AL ships for this exact window, before any of the
  /// workshop's own changes.
  ///
  /// Null when the catalogue has nothing for it -- a configuration the engine
  /// refuses, such as a collar type this window does not offer.
  List<SectionFormulas>? shippedFor(FormulaWindowKey key) {
    final Map<String, List<dynamic>>? sections = _windows[key.windowKey]?[key.configKey];
    if (sections == null) return null;

    final bool isFabrication = key.context == 'fabrication';
    final List<SectionFormulas> out = <SectionFormulas>[];

    // Sorted, so the screen lists profiles in the same order every time; the
    // pieces inside a section keep the engine's order, which is the order they
    // are cut in.
    final List<String> names = sections.keys.toList()..sort();
    for (final String section in names) {
      final List<dynamic> pieces = sections[section]!;
      out.add(SectionFormulas(
        section,
        <FormulaSlot>[
          for (final dynamic piece in pieces)
            FormulaSlot(
              section: section,
              label: (piece as List<dynamic>)[0] as String,
              stored: _formulas[piece[1] as int],
              isFabrication: isFabrication,
            ),
        ],
      ));
    }
    return out;
  }

  /// The panes of glass this window makes, as Quick AL ships them.
  ///
  /// Each pane is a group of two: its height and its width. They are given the
  /// same shape as a profile's pieces so that everything which reads, edits,
  /// saves and resets a formula does so one way -- a pane of glass is not a
  /// special case to a workshop, and should not be one here.
  List<SectionFormulas> shippedGlassFor(FormulaWindowKey key) {
    final List<dynamic>? panes = _glass[key.windowKey]?[key.configKey];
    if (panes == null) return const <SectionFormulas>[];

    final List<SectionFormulas> out = <SectionFormulas>[];
    for (int index = 0; index < panes.length; index++) {
      final Map<String, dynamic> pane = panes[index] as Map<String, dynamic>;
      final String? role = pane['role'] as String?;
      final String height = _formulas[pane['h'] as int];
      final String width = _formulas[pane['w'] as int];

      out.add(SectionFormulas(
        'glass${index + 1}',
        <FormulaSlot>[
          _glassSlot('glass${index + 1}', height),
          _glassSlot('glass${index + 1}', width),
        ],
        displayName: role == null
            ? 'Glass ${index + 1}'
            : 'Glass ${index + 1} · $role',
      ));
    }
    return out;
  }

  /// One side of a pane.
  ///
  /// Named for the measurement it follows, which on a corner window differs
  /// between the two panes: one sits in the left width and one in the right.
  /// The name is worked out from the stored formula rather than passed in, so
  /// it cannot drift from the arithmetic it labels.
  static FormulaSlot _glassSlot(String section, String formula) {
    const Map<String, String> names = <String, String>{
      'h': 'H',
      'w': 'W',
      'wl': 'W_left',
      'wr': 'W_right',
    };

    String label = 'H';
    for (final MapEntry<String, String> entry in names.entries) {
      if (RegExp('(?<![A-Za-z0-9_])${entry.key}(?![A-Za-z0-9_])').hasMatch(formula)) {
        label = entry.value;
        break;
      }
    }

    return FormulaSlot(
      section: section,
      label: label,
      stored: formula,
      isFabrication: true,
      measuresInCentimetres: true,
    );
  }

  /// The shipped formula for one glass side, or null if there is no such pane.
  String? shippedGlassFormulaAt(
    String windowKey,
    String configKey,
    String section,
    int index,
  ) {
    final List<dynamic>? panes = _glass[windowKey]?[configKey];
    if (panes == null) return null;
    final int pane = int.tryParse(section.replaceFirst('glass', '')) ?? 0;
    if (pane < 1 || pane > panes.length || index < 0 || index > 1) return null;
    final Map<String, dynamic> found = panes[pane - 1] as Map<String, dynamic>;
    return _formulas[found[index == 0 ? 'h' : 'w'] as int];
  }

  /// The shipped formula for one piece, or null if there is no such piece.
  String? shippedFormulaAt(String windowKey, String configKey, String section, int index) {
    final List<dynamic>? pieces = _windows[windowKey]?[configKey]?[section];
    if (pieces == null || index < 0 || index >= pieces.length) return null;
    return _formulas[(pieces[index] as List<dynamic>)[1] as int];
  }

  /// Everywhere else this same piece is cut by this same sum.
  ///
  /// A workshop that shortens the sliding window's left upright usually means
  /// it for every collar type, not only the one they happened to have open --
  /// but not always, so this only says where the change *could* go, and the
  /// workshop is asked before it goes there. Matching is by profile, label,
  /// position and the formula they start from: a configuration that already
  /// cuts this piece differently is left alone, because whatever made it
  /// different is not something to quietly overwrite.
  List<String> configsSharing({
    required String windowKey,
    required String section,
    required int index,
    required String label,
    required String formula,
  }) {
    final Map<String, Map<String, List<dynamic>>>? configs = _windows[windowKey];
    if (configs == null) return const <String>[];

    final List<String> found = <String>[];
    configs.forEach((String configKey, Map<String, List<dynamic>> sections) {
      final List<dynamic>? pieces = sections[section];
      if (pieces == null || index >= pieces.length) return;
      final List<dynamic> piece = pieces[index] as List<dynamic>;
      if (piece[0] != label) return;
      if (_formulas[piece[1] as int] != formula) return;
      found.add(configKey);
    });
    return found;
  }

  /// How many pieces this window is cut into, across every profile.
  int pieceCountFor(FormulaWindowKey key) {
    final Map<String, List<dynamic>>? sections = _windows[key.windowKey]?[key.configKey];
    if (sections == null) return 0;
    return sections.values.fold(0, (int sum, List<dynamic> pieces) => sum + pieces.length);
  }
}
